In [1]:
import numpy as np

In [32]:
a = np.array([1,2,3], dtype='int32')

In [13]:
print(a)

[1 2 3]


In [14]:
# number of elements
print(a.size)

3


In [31]:
# size of each element
print(a.itemsize)

4


In [33]:
# get type
a.dtype

dtype('int32')

In [22]:
a.nbytes

6

In [61]:
# created 2d array
b = np.array(
    [
        [1,2,3,4,5,6,7,8,9,10],
        [11,12,13,14,15,16,17,18,19,20]
    ]
)
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [26]:
# check dimensions
b.ndim

2

In [27]:
b.shape

(2, 5)

In [51]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [36]:
# get a specific element
b[1][3]

9

In [38]:
# get a specific row
b[0, :]

array([1, 2, 3, 4, 5])

In [39]:
# get a specific column
b[ : , 4]

array([5, 0])

In [55]:
# more on access [startingIdx, lastIdx, steps]
b[0, 0:8:3]

array([1, 4, 7])

In [59]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 22, 13, 14, 15, 16, 17, 18, 19, 20]])

In [58]:
b[1, 1] = 22
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 22, 13, 14, 15, 16, 17, 18, 19, 20]])

In [63]:
# 3D arrays
c = np.array(
[
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [11,12,13],
        [14,15,16],
        [17,18,19]
    ]
]
)

c[0][1][0]

4

In [67]:
# create zero arrays
np.zeros((4, 5), dtype='int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [69]:
# create one arrays
np.ones((4, 5), dtype='int16')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [70]:
# create one arrays
np.ones((4), dtype='int16')

array([1, 1, 1, 1], dtype=int16)

In [71]:
np.ones((2, 3, 4), dtype='int16')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [72]:
# full with value of 10
np.full((4,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [76]:
# Like array
np.full_like(b, 10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [78]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [84]:
# Random decimal number
np.random.rand(3, 4)

array([[0.24757312, 0.72214779, 0.7556184 , 0.22338892],
       [0.4463114 , 0.72543508, 0.49924128, 0.55261637],
       [0.03465195, 0.70643866, 0.46192139, 0.19230578]])

In [88]:
# Random intiger value
np.random.randint(1, 10 , size=(3, 4))

array([[8, 2, 9, 6],
       [1, 4, 8, 3],
       [7, 6, 4, 5]])

In [89]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
p = np.array([1,2,3,4,5])
q = p   # shallow copy
q = p.copy()  # deep copy
q[2] = 10
p

array([1, 2, 3, 4, 5])

In [93]:
################ mathemetics

In [94]:
p

array([1, 2, 3, 4, 5])

In [95]:
p + 10

array([11, 12, 13, 14, 15])

In [96]:
p - 10

array([-9, -8, -7, -6, -5])

In [97]:
p * 2

array([ 2,  4,  6,  8, 10])

In [98]:
p / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [99]:
p

array([1, 2, 3, 4, 5])

In [100]:
q = np.array([6,7,8,9,10])

In [102]:
p + q

array([ 7,  9, 11, 13, 15])

In [103]:
q = np.array([6,7,8,9,10,11])

In [104]:
p + q

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [126]:
a = np.random.randint(1, 10 , size=(3,4))
a

array([[8, 3, 9, 8],
       [3, 5, 9, 4],
       [2, 8, 2, 8]])

In [127]:
b = np.random.randint(1, 10 , size=(4, 5))
b

array([[3, 3, 7, 6, 2],
       [1, 2, 3, 7, 1],
       [7, 1, 4, 2, 8],
       [5, 3, 8, 6, 2]])

In [128]:
# matrix multiplication
np.matmul(a, b)

array([[130,  63, 165, 135, 107],
       [ 97,  40, 104,  95,  91],
       [ 68,  48, 110, 120,  44]])

In [129]:
a

array([[8, 3, 9, 8],
       [3, 5, 9, 4],
       [2, 8, 2, 8]])

In [130]:
np.min(a)

2

In [131]:
np.max(a)

9

In [134]:
np.sum(a)

69

In [135]:
# column sum
np.sum(a, axis=0)

array([13, 16, 20, 20])

In [136]:
# row sum
np.sum(a, axis=1)

array([28, 21, 20])

In [140]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.vstack([a, b, a, b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [141]:
a = np.ones((2,2))
b = np.zeros((2,4))

In [142]:
a

array([[1., 1.],
       [1., 1.]])

In [143]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
np.hstack([a, b])

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.]])

In [148]:
# Create an array of 10 zeros and set the fifth value to 1
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [149]:
# Create an array and reverse it
a=np.array([1,2,3,4,5,6])
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [150]:
# Create a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [153]:
# Generate a 3x3x3 array with random values
np.random.randint(1,10, size=(3,3,3))

array([[[6, 2, 8],
        [7, 9, 6],
        [6, 6, 5]],

       [[5, 2, 8],
        [4, 8, 5],
        [9, 7, 9]],

       [[7, 9, 6],
        [8, 5, 3],
        [8, 3, 9]]])

In [154]:
# Find the mean
arr = np.array([1, 2, 3, 4, 5])
np.mean(arr)

3.0

In [155]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

np.intersect1d(a, b)

array([3, 4])

In [157]:
arr = np.array([1, 2, 3, 4, 5])
# Replace odd numbers with -1
arr[arr % 2 == 1] = -1
arr

array([-1,  2, -1,  4, -1])

In [158]:
# Create a NumPy array with values from 10 to 49
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [162]:
# Reshape the array [0..8] into a 3x3 matrix
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
arr = np.array([3, 5, 7, 9])
# Replace elements greater than 5 with 0
arr[arr>5] = 0
arr

array([3, 5, 0, 0])

In [165]:
arr = np.array([0, 1, 0, 3, 0, 5])
# Get indices of non-zero elements
np.nonzero(arr)

(array([1, 3, 5]),)